<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" ignored="3" total="12" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="AT_Suite" duration-ms="530637" started-at="2020-06-04T01:07:31 IST" finished-at="2020-06-04T01:16:21 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="530637" started-at="2020-06-04T01:07:31 IST" finished-at="2020-06-04T01:16:21 IST">
      <class name="WT_Testcases.ExtentDemo">
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:WT_Testcases.ExtentDemo@4e1d422d]" name="BeforeMethod" is-config="true" duration-ms="27967" started-at="2020-06-04T01:11:33 IST" finished-at="2020-06-04T01:12:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="myCase(java.util.LinkedHashMap)[pri:0, instance:WT_Testcases.ExtentDemo@4e1d422d]" name="myCase" duration-ms="41273" started-at="2020-06-04T01:12:00 IST" data-provider="userData" finished-at="2020-06-04T01:12:42 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{username=rautsumit, password=rautsumit}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed with addFailLog method rautsumitcould not be entered in inutbox]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed with addFailLog method rautsumitcould not be entered in inutbox
at org.testng.Assert.fail(Assert.java:97)
at Utilities.ElementUtil.addFailLog(ElementUtil.java:402)
at Utilities.ElementUtil.doSendKeys(ElementUtil.java:300)
at WT_Pages.WT_LoginPage.enterUsername(WT_LoginPage.java:28)
at WT_Testcases.ExtentDemo.myCase(ExtentDemo.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myCase -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:WT_Testcases.ExtentDemo@4e1d422d]" name="afterMethod" is-config="true" duration-ms="1486" started-at="2020-06-04T01:12:42 IST" finished-at="2020-06-04T01:12:43 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=myCase status=FAILURE method=ExtentDemo.myCase(java.util.LinkedHashMap)[pri:0, instance:WT_Testcases.ExtentDemo@4e1d422d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- WT_Testcases.ExtentDemo -->
      <class name="WT_Testcases.ExtentDemo2">
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:WT_Testcases.ExtentDemo2@66480dd7]" name="BeforeMethod" is-config="true" duration-ms="25240" started-at="2020-06-04T01:12:43 IST" finished-at="2020-06-04T01:13:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="myCase(java.util.LinkedHashMap)[pri:0, instance:WT_Testcases.ExtentDemo2@66480dd7]" name="myCase" duration-ms="41254" started-at="2020-06-04T01:13:09 IST" data-provider="userData" finished-at="2020-06-04T01:13:50 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{username=rautsumit, password=rautsumit}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed with addFailLog method rautsumitcould not be entered in inutbox]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed with addFailLog method rautsumitcould not be entered in inutbox
at org.testng.Assert.fail(Assert.java:97)
at Utilities.ElementUtil.addFailLog(ElementUtil.java:402)
at Utilities.ElementUtil.doSendKeys(ElementUtil.java:300)
at WT_Pages.WT_LoginPage.enterUsername(WT_LoginPage.java:28)
at WT_Testcases.ExtentDemo2.myCase(ExtentDemo2.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myCase -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:WT_Testcases.ExtentDemo2@66480dd7]" name="afterMethod" is-config="true" duration-ms="1500" started-at="2020-06-04T01:13:50 IST" finished-at="2020-06-04T01:13:51 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=myCase status=FAILURE method=ExtentDemo2.myCase(java.util.LinkedHashMap)[pri:0, instance:WT_Testcases.ExtentDemo2@66480dd7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- WT_Testcases.ExtentDemo2 -->
      <class name="AP_TestCases.AP_RegressionTest">
        <test-method status="PASS" signature="setExtent()[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="setExtent" is-config="true" duration-ms="157" started-at="2020-06-04T01:07:31 IST" finished-at="2020-06-04T01:07:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="BeforeMethod" is-config="true" duration-ms="32224" started-at="2020-06-04T01:07:32 IST" finished-at="2020-06-04T01:08:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="PASS" signature="AT_01_NewAccount(java.util.LinkedHashMap)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="AT_01_NewAccount" duration-ms="9975" started-at="2020-06-04T01:08:04 IST" data-provider="userData" finished-at="2020-06-04T01:08:14 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{emailaddress=rautsumit@test.com, gender=male, firstname=sumit, lastname=raut, password=pwd}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AT_01_NewAccount -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="afterMethod" is-config="true" duration-ms="1331" started-at="2020-06-04T01:08:14 IST" finished-at="2020-06-04T01:08:15 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AT_01_NewAccount status=SUCCESS method=AP_RegressionTest.AT_01_NewAccount(java.util.LinkedHashMap)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="BeforeMethod" is-config="true" duration-ms="30370" started-at="2020-06-04T01:08:15 IST" finished-at="2020-06-04T01:08:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="PASS" signature="AT_01_NewAccount(java.util.LinkedHashMap)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="AT_01_NewAccount" duration-ms="9226" started-at="2020-06-04T01:08:46 IST" data-provider="userData" finished-at="2020-06-04T01:08:55 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{emailaddress=rautsumit@test.com, gender=male, firstname=sumit, lastname=raut, password=pwd}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AT_01_NewAccount -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="afterMethod" is-config="true" duration-ms="844" started-at="2020-06-04T01:08:55 IST" finished-at="2020-06-04T01:08:56 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AT_01_NewAccount status=SUCCESS method=AP_RegressionTest.AT_01_NewAccount(java.util.LinkedHashMap)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="BeforeMethod" is-config="true" duration-ms="31933" started-at="2020-06-04T01:08:56 IST" finished-at="2020-06-04T01:09:28 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="AT_01_NewAccount(java.util.LinkedHashMap)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="AT_01_NewAccount" duration-ms="26887" started-at="2020-06-04T01:09:28 IST" data-provider="userData" finished-at="2020-06-04T01:09:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{emailaddress=s@s.com, gender=male, firstname=sumit, lastname=raut, password=pwd}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for visibility of element located by By.xpath: //*[contains(text(),'Your personal information')] (tried for 20 second(s) with 500 milliseconds interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //*[contains(text(),'Your personal information')] (tried for 20 second(s) with 500 milliseconds interval)
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
at Utilities.ElementUtil.waitForElementVisibilityByLocator(ElementUtil.java:70)
at AP_Pages.AP_AccountCreation.verifyAP_AccountCreation_Visible(AP_AccountCreation.java:25)
at AP_TestCases.AP_RegressionTest.AT_01_NewAccount(AP_RegressionTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(),'Your personal information')]"}
  (Session info: chrome=83.0.4103.61)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-G0D562V', ip: '192.168.0.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.61, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: C:\Users\sunshine\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:59851}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 9d0196e3b46447f913010661fb76cdf6
*** Element info: {Using=xpath, value=//*[contains(text(),'Your personal information')]}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
... 35 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AT_01_NewAccount -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="afterMethod" is-config="true" duration-ms="1218" started-at="2020-06-04T01:09:55 IST" finished-at="2020-06-04T01:09:56 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AT_01_NewAccount status=FAILURE method=AP_RegressionTest.AT_01_NewAccount(java.util.LinkedHashMap)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="BeforeMethod" is-config="true" duration-ms="27047" started-at="2020-06-04T01:09:56 IST" finished-at="2020-06-04T01:10:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="AT_01_NewAccount(java.util.LinkedHashMap)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="AT_01_NewAccount" duration-ms="26941" started-at="2020-06-04T01:10:23 IST" data-provider="userData" finished-at="2020-06-04T01:10:50 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{emailaddress=s@s.com, gender=male, firstname=sumit, lastname=raut, password=pwd}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for visibility of element located by By.xpath: //*[contains(text(),'Your personal information')] (tried for 20 second(s) with 500 milliseconds interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //*[contains(text(),'Your personal information')] (tried for 20 second(s) with 500 milliseconds interval)
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
at Utilities.ElementUtil.waitForElementVisibilityByLocator(ElementUtil.java:70)
at AP_Pages.AP_AccountCreation.verifyAP_AccountCreation_Visible(AP_AccountCreation.java:25)
at AP_TestCases.AP_RegressionTest.AT_01_NewAccount(AP_RegressionTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(),'Your personal information')]"}
  (Session info: chrome=83.0.4103.61)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-G0D562V', ip: '192.168.0.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.61, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: C:\Users\sunshine\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:59933}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 5ae29ba90b2c0baf259e5055beb1afc3
*** Element info: {Using=xpath, value=//*[contains(text(),'Your personal information')]}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
... 35 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AT_01_NewAccount -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="afterMethod" is-config="true" duration-ms="1172" started-at="2020-06-04T01:10:50 IST" finished-at="2020-06-04T01:10:51 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AT_01_NewAccount status=FAILURE method=AP_RegressionTest.AT_01_NewAccount(java.util.LinkedHashMap)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="BeforeMethod" is-config="true" duration-ms="30586" started-at="2020-06-04T01:10:51 IST" finished-at="2020-06-04T01:11:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="PASS" signature="AT_01_NewAccount(java.util.LinkedHashMap)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="AT_01_NewAccount" duration-ms="10054" started-at="2020-06-04T01:11:21 IST" data-provider="userData" finished-at="2020-06-04T01:11:32 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{emailaddress=rautsumit@test.com, gender=male, firstname=sumit, lastname=raut, password=pwd}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AT_01_NewAccount -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23]" name="afterMethod" is-config="true" duration-ms="859" started-at="2020-06-04T01:11:32 IST" finished-at="2020-06-04T01:11:32 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=AT_01_NewAccount status=SUCCESS method=AP_RegressionTest.AT_01_NewAccount(java.util.LinkedHashMap)[pri:0, instance:AP_TestCases.AP_RegressionTest@3327bd23] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- AP_TestCases.AP_RegressionTest -->
      <class name="WT_Testcases.WT_RegressionTest">
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:WT_Testcases.WT_RegressionTest@52a86356]" name="BeforeMethod" is-config="true" duration-ms="35165" started-at="2020-06-04T01:13:51 IST" finished-at="2020-06-04T01:14:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="WT_Register(java.util.LinkedHashMap)[pri:0, instance:WT_Testcases.WT_RegressionTest@52a86356]" name="WT_Register" duration-ms="41273" started-at="2020-06-04T01:14:27 IST" data-provider="userData" finished-at="2020-06-04T01:15:08 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{username=rautsumit, password=rautsumit, type=na, passengers=2, departing_from=London, departing_month=June, departing_day=1, arriving_in=New yok , returning_month=6, returning_day=3, preferences=Business class, airline=Unified Airlines}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed with addFailLog method rautsumitcould not be entered in inutbox]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed with addFailLog method rautsumitcould not be entered in inutbox
at org.testng.Assert.fail(Assert.java:97)
at Utilities.ElementUtil.addFailLog(ElementUtil.java:402)
at Utilities.ElementUtil.doSendKeys(ElementUtil.java:300)
at WT_Pages.WT_LoginPage.enterUsername(WT_LoginPage.java:28)
at WT_Testcases.WT_RegressionTest.WT_Register(WT_RegressionTest.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WT_Register -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:WT_Testcases.WT_RegressionTest@52a86356]" name="afterMethod" is-config="true" duration-ms="1517" started-at="2020-06-04T01:15:08 IST" finished-at="2020-06-04T01:15:09 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=WT_Register status=FAILURE method=WT_RegressionTest.WT_Register(java.util.LinkedHashMap)[pri:0, instance:WT_Testcases.WT_RegressionTest@52a86356] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:WT_Testcases.WT_RegressionTest@52a86356]" name="BeforeMethod" is-config="true" duration-ms="29001" started-at="2020-06-04T01:15:09 IST" finished-at="2020-06-04T01:15:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="myCase(java.util.LinkedHashMap)[pri:0, instance:WT_Testcases.WT_RegressionTest@52a86356]" name="myCase" duration-ms="41283" started-at="2020-06-04T01:15:38 IST" data-provider="userData" finished-at="2020-06-04T01:16:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{username=rautsumit, password=rautsumit}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed with addFailLog method rautsumitcould not be entered in inutbox]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed with addFailLog method rautsumitcould not be entered in inutbox
at org.testng.Assert.fail(Assert.java:97)
at Utilities.ElementUtil.addFailLog(ElementUtil.java:402)
at Utilities.ElementUtil.doSendKeys(ElementUtil.java:300)
at WT_Pages.WT_LoginPage.enterUsername(WT_LoginPage.java:28)
at WT_Testcases.WT_RegressionTest.myCase(WT_RegressionTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myCase -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:WT_Testcases.WT_RegressionTest@52a86356]" name="afterMethod" is-config="true" duration-ms="1525" started-at="2020-06-04T01:16:20 IST" finished-at="2020-06-04T01:16:21 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=myCase status=FAILURE method=WT_RegressionTest.myCase(java.util.LinkedHashMap)[pri:0, instance:WT_Testcases.WT_RegressionTest@52a86356] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- WT_Testcases.WT_RegressionTest -->
    </test> <!-- Test -->
  </suite> <!-- AT_Suite -->
</testng-results>
